Move Alpine post-setup hack BEFORE checkout action
Checkount action fails unless we fool GitHub this is not alpine linux
The error is
Error: JavaScript Actions in Alpine containers are only supported on x64 Linux runners. Detected Linux Arm64

So we need to rearrange steps a bit to make post setup run before cleanup
Install bash
Setup deps
Post setup
Full checkout
Free diskspace