Enable using self-hosted runners (#11075)
* Test self-hosted small runner

* Fix env

* Medium runner

* Fix medium runner

* medium with dynamic labels

* Small runner, 1 instance

* small runner, 10 instances

* Small runner, 40 instances

* Use self-hosted runners with fallback to RUNS_ON or hard-coded label

* Remove self-hosted-test

* Disable mounting and cleanup in container

This leads to errors with the rootless docker

* Remove cleanup from the containers

* Use github-hosted for MIRI to identify error

* Debug MIRI sysroot failures

* Remove miri cache from the image

* Universal cleanup action

* Fix cleanup error

* Try to fix alpine workaround to work in rootless environment

* Move Alpine post-setup hack BEFORE checkout action

Checkount action fails unless we fool GitHub this is not alpine linux
The error is
Error: JavaScript Actions in Alpine containers are only supported on x64 Linux runners. Detected Linux Arm64

So we need to rearrange steps a bit to make post setup run before cleanup
Install bash
Setup deps
Post setup
Full checkout
Free diskspace

* Move setup step before checkout